function genShape2D( outFileName )
% function genShape2D( outFileName )
%
% Kontur als Polygon berechnen und Ausgabe in openscad-Syntax.
% Dort kann dann durch Extrusion darus ein Rotationskoerper
% mit der Wandstaerke w erzeugt werden.
%
% Usage example:
%   % octave
%   genShape2D
%   
%   // openscad
%   rotate_extrude($fn = 80) rotate([0,0,90]) include <poly.scad>
%

pkg load signal            % need rms function
close all

shape=0;

outFileName='poly.scad';
comment=sprintf('generated by genShape2D.m, shape = %d', shape);

w=0.8;     % Wall thickness

switch shape
  case {1}
    x=[ 0  5  10 20 ]
    y=[ 20 10 10 10 ]

  case {2}
    x=[ 0  20 30 40 50 80 ]
    y=[ 35 35 31 14 10 10 ]

  case {3}
    x=[ 0  20  50 80 ]
    y=[ 35 35  10 9 ]/2

  case {4}
    % half circle
    r=50
    x=  0:2:2*r;
    y=  r*sqrt(1-(x/r -1).^2);
    ti= 0:pi/30:pi;        % parametrische Definition
    xi= r*(cos(ti)+1);
    yi= r*sin(ti);

  otherwise
    % exponential horn
    a=50;
    L=150;
    b=2.7/L;
    x=  0:10:L;
    y= a*exp(-x*b);
    xi= 0:1:L;
    yi=a*exp(-xi*b);

end

figure, plot(x,y); hold on

if ~exist('xi', 'var')
  xi=0:0.2:x(end);
end
if ~exist('yi', 'var')
  yi=interp1(x,y,xi,'cubic')
end
size(xi)
size(yi)
plot(xi,yi,'+-'); ylim([0 55]);

% Um Wandstaerke verschobene Kontour berechnen.
% das funktioniert nicht mehr, wenn der Kruemmungsradius kleiner als w ist.
%s=[x ; y];
s=[xi ; yi];
ds=diff(s,1,2);
O=[0 ; 0]
ds = [ O ds] + [ds O]/2;    % FIR filter
ds = ds ./ (ones(2,1)*rms(ds,1))/sqrt(2);  % Tangenten-Einheitsvektor
T=[ 0 -1 ; 1 0];
dn  = T*ds;                                % Normalenvektor
%sqrt(dn(1,:).^2 + dn(2,:).^2);
so = s + w*dn;

iyneg=find(so(2,:) < 0);
so(2,iyneg)=0;

plot(so(1,:),so(2,:),'x-'); hold off
s=[ s fliplr(so) ];

% openscad polygon output
fh=fopen(outFileName,'w');
%fh=1;
fprintf(fh, '// %s\npolygon([ \n', comment);
semic=',';
cnt=1;
for ii=1:length(s)
  x0=s(1,ii);
  y0=s(2,ii);
  if ii == length(s)
    semic=' ';
  end 
  fprintf(fh, ' [ %6.3f, %6.3f]%s', x0, y0, semic);
  if mod(ii, 4) == 0
    fprintf(fh, '\n');
  end
end
fprintf(fh, ' ]);\n\n');
fclose(fh);
